import { test, expect, type Page } from '@playwright/test'

async function start(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await page.getByRole('button', { name: 'Naar oefening 1', exact: true }).click()
}
async function later(page: Page) {
  await page.getByRole('button', { name: 'Lukt niet', exact: true }).click()
  await page.getByRole('button', { name: 'Bezet', exact: true }).click()
  await page.getByRole('button', { name: 'Later doen', exact: true }).click()
}
test('later doen en minder tijd bewaren concept en open sets na offline heropenen', async ({ page, context, browserName }) => {
  await start(page)
  await page.getByRole('textbox', { name: 'Gewicht (kg)', exact: true }).fill('17,5')
  await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
  await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
  await later(page)
  await expect(page.getByRole('heading', { name: 'Leg curl', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Minder tijd', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('checkbox')).toHaveCount(7)
  for (const checkbox of await dialog.getByRole('checkbox').all()) {
    const label = await checkbox.evaluate(input => input.parentElement?.textContent)
    if (!label?.includes('Leg press')) await checkbox.check()
  }
  await dialog.getByRole('button', { name: 'Bekijk het gevolg' }).click()
  await expect(dialog.getByText('Volgende training ongewijzigd.')).toBeVisible()
  await dialog.getByRole('button', { name: 'Accepteren', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Leg press', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('17,5')
  await expect(page.getByText('App offline beschikbaar', { exact: true })).toBeVisible()
  if (browserName === 'chromium') await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('17,5')
  await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
  await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
  await page.getByRole('button', { name: 'Aanpassing terugdraaien' }).click()
  await page.getByRole('button', { name: 'Terugdraaien', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Leg curl', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pauzeren of stoppen' }).click()
  await page.getByRole('button', { name: 'Afronden met wat ik heb gedaan' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Sessie afronden', exact: true }).click()
  await expect(page.getByText('Set 1: 17,5 kg × 10', { exact: true })).toBeVisible()
  await expect(page.getByText('0 overgeslagen · 13 niet afgemaakt.')).toBeVisible()
})

test('dagvormdoel blijft apart van invoer en browser-terug annuleert een voorstel', async ({ page }) => {
  await start(page)
  await page.getByRole('textbox', { name: 'Gewicht (kg)', exact: true }).fill('12')
  await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
  await page.getByRole('button', { name: 'Te zwaar', exact: true }).click()
  await page.getByRole('button', { name: 'Dagvorm', exact: true }).click()
  await page.getByRole('button', { name: 'Doel vandaag gebruiken' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
  await page.getByRole('textbox', { name: 'Doelgewicht (kg)' }).fill('10')
  await page.getByRole('button', { name: 'Doel vandaag gebruiken' }).click()
  await expect(page.getByText('Doel vandaag: 10 kg', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('12')
  await page.getByRole('button', { name: 'Lukt niet', exact: true }).click()
  await page.getByRole('button', { name: 'Pijn', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('12')
  await page.reload()
  await expect(page.getByText('Doel vandaag: 10 kg', { exact: true })).toBeVisible()
})

test('afspraak verplaatsen, inkorten en overslaan bewaren datum en oorspronkelijke planning', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Pas vandaag aan' }).click()
  await page.getByRole('button', { name: 'Training verplaatsen', exact: true }).click()
  await page.getByLabel('Nieuwe datum').fill('2099-06-20')
  await page.getByRole('button', { name: 'Bekijk het gevolg' }).click()
  await page.getByRole('button', { name: 'Verplaatsen', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText(/zaterdag 20 juni/).first()).toBeVisible()
  await page.getByRole('button', { name: 'Pas vandaag aan' }).click()
  await page.getByRole('button', { name: 'Ik heb minder tijd' }).click()
  await page.getByRole('checkbox', { name: 'Leg press · 2 open sets' }).check()
  await page.getByRole('button', { name: 'Bekijk het gevolg' }).click()
  await page.getByRole('button', { name: 'Accepteren', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('Alleen deze afspraak: Leg press vervalt.')).toBeVisible()
  await page.getByRole('button', { name: 'Pas vandaag aan' }).click()
  await page.getByRole('button', { name: 'Ik sla vandaag over' }).click()
  await page.getByRole('button', { name: 'Ja, deze training overslaan' }).click()
  await expect(page.getByRole('heading', { name: 'Training overgeslagen' })).toBeVisible()
  await page.getByRole('button', { name: 'Volgende training bekijken' }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByText('Vaste training', { exact: true })).toBeVisible()
  await expect(page.getByText(/Eenmalig verplaatst vanaf/)).toBeVisible()
  await expect(page.getByText(/zaterdag 20 juni · Overgeslagen/)).toBeVisible()
})

test('verouderde aanpassing wordt niet toegepast en opslagfout kan opnieuw geprobeerd worden', async ({ page, context }) => {
  await start(page)
  const other = await context.newPage()
  await other.goto(page.url())
  await other.getByRole('button', { name: 'Lukt niet', exact: true }).click()
  await other.getByRole('button', { name: 'Bezet', exact: true }).click()
  await later(page)
  await other.getByRole('button', { name: 'Later doen', exact: true }).click()
  await expect(other.getByRole('dialog').getByRole('alert')).toContainText('ander venster')
  await other.close()
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    let fail = true
    IDBObjectStore.prototype.put = function (...args) {
      if (this.name === 'workoutOutbox' && fail) { fail = false; throw new DOMException('Test quota', 'QuotaExceededError') }
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: 'Lukt niet', exact: true }).click()
  await page.getByRole('button', { name: 'Geen materiaal', exact: true }).click()
  await page.getByRole('button', { name: 'Resterende sets overslaan' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('opslag is vol')
  await page.getByRole('button', { name: 'Resterende sets overslaan' }).click()
  await expect(page.getByRole('heading', { name: 'Chest press', exact: true })).toBeVisible()
})
