import { test, expect, chromium, webkit } from '@playwright/test'
import { mkdtemp, realpath, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { basename, dirname, join } from 'node:path'

test('Vandaag, Plan, concept, sheet, pauzeren en hervatten behouden context', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Bekijk de sessie', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Je full-body training' })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Start training', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Bekijk de oefeningen' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Trainingsdagen aanpassen' }).click()
  await page.getByRole('radio', { name: 'Zaterdag', exact: true }).check()
  await expect(page.getByRole('button', { name: 'Planning opslaan' })).toBeEnabled()
  await page.reload()
  await expect(page.getByRole('radio', { name: 'Zaterdag', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Annuleren' }).click()
  await expect(page.getByText('Niet ingepland', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Trainingsdagen aanpassen' }).click()
  await page.getByRole('radio', { name: 'Zondag', exact: true }).check()
  await page.getByRole('button', { name: 'Planning opslaan' }).click()
  await page.getByRole('button', { name: 'Vandaag', exact: true }).click()
  await expect(page.getByText('Zondag staat in je planning.')).toBeVisible()
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Gedaan', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Gedaan', exact: true })).toBeChecked()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: 'Gedaan', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Naar oefening 1' }).click()
  await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('15,')
  await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
  await page.getByRole('button', { name: /Oefendemonstratie/ }).click()
  await page.getByRole('button', { name: 'Terug naar de set' }).click()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('15,')
  await page.getByRole('button', { name: 'Pauzeren of stoppen' }).click()
  await page.getByRole('button', { name: 'Sessie pauzeren' }).click()
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Vandaag', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sessie gepauzeerd' })).toBeVisible()
  await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Verder trainen', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('15,')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Naar Vandaag · sessie blijft lopen' }).click()
  await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Verder trainen', exact: true }).click()
  await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
  await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Vul een gewicht in')
  await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('15,5')
  await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
  await expect(page.getByRole('timer')).toBeVisible()
})

test('hele training, dubbel bevestigen, verlopen rust, geweigerde wake lock en vorige registratie', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => Object.defineProperty(navigator, 'wakeLock', { value: { request: () => Promise.reject(new DOMException('Test denial', 'NotAllowedError')) } }))
  await page.clock.install({ time: new Date('2026-09-17T18:00:00Z') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await page.getByRole('button', { name: 'Naar oefening 1' }).click()
  for (let index = 0; index < 14; index++) {
    await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('12,5')
    await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
    await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
    if (index === 0) {
      await page.getByRole('button', { name: 'Set vastleggen', exact: true }).evaluate(button => { if (button instanceof HTMLButtonElement) { button.click(); button.click() } })
      await expect(page.getByRole('timer')).toHaveText('2:00')
      await page.getByRole('checkbox', { name: 'Scherm aanhouden tijdens rust' }).check()
      await expect(page.getByText('Scherm aanhouden lukt niet. Houd zelf je scherm actief.')).toBeVisible()
      await page.clock.fastForward(121_000)
      await expect(page.getByRole('heading', { name: 'Rust voorbij', exact: true })).toBeVisible()
      await page.getByRole('button', { name: '30 seconden extra rust' }).click()
      await expect(page.getByRole('timer')).toHaveText('0:30')
    } else await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
    if (index < 13) await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
  }
  await expect(page.getByRole('heading', { name: 'Alle sets vastgelegd' })).toBeVisible()
  await expect(page.getByText('Je sessie loopt nog tot je deze afrondt.')).toBeVisible()
  await page.getByRole('button', { name: 'Sessie afronden', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Sessie afronden', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sessie afgerond', exact: true })).toBeVisible()
  await expect(page.getByText('14 van 14 werksets vastgelegd.')).toBeVisible()
  await page.reload()
  await expect(page.getByText('14 van 14 werksets vastgelegd.')).toBeVisible()
  await page.getByRole('button', { name: 'Wat betekent dit?' }).click()
  await page.getByRole('button', { name: 'Terug naar Vandaag', exact: true }).click()
  await page.getByRole('button', { name: 'Volgende training starten' }).click()
  await page.getByRole('button', { name: 'Naar oefening 1' }).click()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('')
  await expect(page.getByText('Vorige registratie van set 1: 12,5 kg × 10. Alleen vergelijkbaar op hetzelfde apparaat.')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('m2-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})

for (const ending of ['Afronden met wat ik heb gedaan', 'Afbreken']) {
  test(`gedeeltelijke sessie: ${ending}, conceptwaarschuwing en behoud van uitgevoerde sets`, async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: 'Start training', exact: true }).click()
    await page.getByRole('button', { name: 'Naar oefening 1' }).click()
    await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('10')
    await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('9')
    await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
    await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('11,')
    await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
    await page.getByRole('button', { name: 'Pauzeren of stoppen' }).click()
    await page.getByRole('button', { name: ending, exact: true }).click()
    await expect(page.getByText(/Er staat nog invoer die niet is vastgelegd/)).toBeVisible()
    await page.getByRole('dialog').getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('11,')
    await page.getByRole('button', { name: 'Pauzeren of stoppen' }).click()
    await page.getByRole('button', { name: ending, exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: ending === 'Afbreken' ? 'Sessie afbreken' : 'Sessie afronden', exact: true }).click()
    await expect(page.getByRole('heading', { name: ending === 'Afbreken' ? 'Sessie afgebroken' : 'Sessie deels afgerond', exact: true })).toBeVisible()
    await expect(page.getByText('Set 1: 10 kg × 9', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByText('1 van 14 werksets vastgelegd.')).toBeVisible()
  })
}

test('opslagfout bewaart invoer, houdt navigatie tegen en is opnieuw te proberen', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await page.getByRole('button', { name: 'Naar oefening 1' }).click()
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    let fail = true
    IDBObjectStore.prototype.put = function (...args) {
      if (this.name === 'drafts' && fail) { fail = false; throw new DOMException('Test quota', 'QuotaExceededError') }
      return original.apply(this, args)
    }
  })
  await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('12')
  await expect(page.getByRole('alert')).toContainText('opslag is vol')
  await expect(page.getByRole('button', { name: 'Naar Vandaag · sessie blijft lopen' })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
  await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
  await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
  await expect(page.getByRole('cell', { name: '12 kg × 10', exact: true })).toBeVisible()
})

test('twee vensters bewaren de afgewezen invoer ook wanneer het andere venster de set bevestigt', async ({ page, context }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start training', exact: true }).click()
  await page.getByRole('button', { name: 'Naar oefening 1' }).click()
  const other = await context.newPage()
  await other.goto(page.url())
  await expect(other.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('')
  await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('12')
  await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
  await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
  await other.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('19,')
  await expect(other.getByRole('alert')).toContainText('andere conceptinvoer')
  await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
  await expect(page.getByRole('timer')).toBeVisible()
  await expect(other.getByText('Jouw invoer: 19, kg · geen herhalingen.')).toBeVisible()
  await other.getByRole('button', { name: 'Actuele sessie openen' }).click()
  await expect(other.getByRole('cell', { name: '12 kg × 10', exact: true })).toBeVisible()
})

test('browser sluiten en offline heropenen behoudt actieve rust en later conceptinvoer', async ({ browserName }) => {
  const browserType = browserName === 'webkit' ? webkit : chromium
  const profile = await mkdtemp(join(tmpdir(), 'fitness-m2-'))
  const options = { headless: true, viewport: { width: 375, height: 812 } }
  let context = await browserType.launchPersistentContext(profile, options)
  try {
    let page = await context.newPage()
    await page.goto('http://127.0.0.1:4173/')
    await page.getByRole('button', { name: 'Start training', exact: true }).click()
    await page.getByRole('button', { name: 'Naar oefening 1' }).click()
    await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('12,5')
    await page.getByRole('textbox', { name: 'Herhalingen', exact: true }).fill('10')
    await page.getByRole('button', { name: 'Set vastleggen', exact: true }).click()
    await expect(page.getByRole('timer')).toBeVisible()
    await expect(page.getByText('App offline beschikbaar', { exact: true })).toBeVisible()
    await context.close()
    context = await browserType.launchPersistentContext(profile, options)
    await context.setOffline(true)
    page = await context.newPage()
    await page.goto('http://127.0.0.1:4173/')
    await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await expect(page.getByRole('cell', { name: '12,5 kg × 10', exact: true })).toBeVisible()
    await expect(page.getByRole('timer')).toHaveText(/^[01]:\d\d$/)
    await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await page.getByRole('textbox', { name: 'Gewicht (kg)' }).fill('16,')
    await expect(page.getByRole('status')).toHaveText('Concept op apparaat opgeslagen')
    await context.close()
    context = await browserType.launchPersistentContext(profile, options)
    await context.setOffline(true)
    page = await context.newPage()
    await page.goto('http://127.0.0.1:4173/')
    await page.getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Verder trainen', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Gewicht (kg)' })).toHaveValue('16,')
  } finally {
    await context.close()
    const resolved = await realpath(profile)
    if (dirname(resolved) !== await realpath(tmpdir()) || !basename(resolved).startsWith('fitness-m2-')) throw new Error('Onverwachte testmap, niet verwijderd.')
    await rm(resolved, { recursive: true, maxRetries: 3, retryDelay: 300 })
  }
})
